### ISSUE TITLE
forceinline not working

### ISSUE THREAD

**Issue by XenocodeRCE** [pjc0247/lookatme#1]
hello

forceInlining protection seems to have a very little applicability due to its incompatibility with a lot of method

can you fix this ? do you need file to test ?

**Comment by pjc0247** [comment]
Hi!
First of all, this project is made for studying purpose with very limited number of test cases.
It may not work with all .NET binaries.

However, I can make a fix if it does not take a lots of time.
Could you attach or send your `exe` file?
I'll take a look and give you a reply.

Thanks.

**Comment by XenocodeRCE** [comment]
Hello, here is a test file I use for all of my obfuscation-related project.

[RegexTester0.zip](https://github.com/pjc0247/lookatme/files/3246017/RegexTester0.zip)

Have a wonderful day 🙏

**Comment by pjc0247** [comment]
https://github.com/pjc0247/lookatme/commit/71cf49255ba4c7f453a9530f1f4fb3821755f186

Hi, I made a fix and pushed it.
It was caused by my mistake, I taught `calli` is `call instance` but it was `call native`. So I made another checking routine and it works now.

Even I made 2 more fixes after that, it still not working. It will be a hard job to make it perfect.

Since this project is made for my private studying purpose, I don't have any plans to improve it at this moment. Please use other solutions or just use it for reference purpose.

Thanks.

**Comment by XenocodeRCE** [comment]
I can fork it and make pull request for sure. peace on you
